// generated by tools/build-index — do not edit
import type { Team } from "../index.js";
export const teams: readonly Team[] = [
  {"league":"aaf","team_id":"719","abbr":null,"name":"Arizona Hotshots","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#144734","color_secondary":"#ffb71b","color_source":"logo"},
  {"league":"aaf","team_id":"720","abbr":null,"name":"Atlanta Legends","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#c5b683","color_secondary":"#ffffff","color_source":"logo"},
  {"league":"aaf","team_id":"721","abbr":null,"name":"Birmingham Iron","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#79858b","color_secondary":"#c7c7c7","color_source":"logo"},
  {"league":"aaf","team_id":"722","abbr":null,"name":"Memphis Express","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#0b2240","color_secondary":"#cf152d","color_source":"logo"},
  {"league":"aaf","team_id":"723","abbr":null,"name":"Orlando Apollos","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#0b2240","color_secondary":"#fc5000","color_source":"logo"},
  {"league":"aaf","team_id":"724","abbr":null,"name":"Salt Lake Stallions","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#0033a0","color_secondary":"#3c97cb","color_source":"logo"},
  {"league":"aaf","team_id":"725","abbr":null,"name":"San Antonio Commanders","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#691b33","color_secondary":"#cf152d","color_source":"logo"},
  {"league":"aaf","team_id":"726","abbr":null,"name":"San Diego Fleet","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#303e48","color_secondary":"#fec526","color_source":"logo"}
] as const satisfies readonly Team[];
