// generated by tools/build-index — do not edit
import type { Team } from "../index.js";
export const teams: readonly Team[] = [
  {"league":"phf","team_id":"124984","abbr":null,"name":"Metropolitan Riveters","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#0e2039","color_secondary":"#47485b","color_source":"logo"},
  {"league":"phf","team_id":"207478","abbr":null,"name":"Montreal Force","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#901b39","color_secondary":"#a46d86","color_source":"logo"},
  {"league":"phf","team_id":"61635","abbr":null,"name":"Buffalo Beauts","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#7f7f7f","color_secondary":"#000000","color_source":"logo"},
  {"league":"phf","team_id":"61636","abbr":null,"name":"Metropolitan Riveters","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#f6dfa4","color_secondary":"#00609c","color_source":"logo"},
  {"league":"phf","team_id":"61637","abbr":null,"name":"Connecticut Whale","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#1a6492","color_secondary":"#006f3c","color_source":"logo"},
  {"league":"phf","team_id":"61638","abbr":null,"name":"Boston Pride","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#897d61","color_secondary":"#bda87d","color_source":"logo"},
  {"league":"phf","team_id":"61639","abbr":null,"name":"Minnesota Whitecaps","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#1b449c","color_secondary":"#7b91c1","color_source":"logo"},
  {"league":"phf","team_id":"79963","abbr":null,"name":"Toronto Six","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#ed2229","color_secondary":null,"color_source":"logo"}
] as const satisfies readonly Team[];
