// generated by tools/build-index — do not edit
import type { Team } from "../index.js";
export const teams: readonly Team[] = [
  {"league":"pwhl","team_id":"1","abbr":null,"name":"Boston Fleet","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#081d2b","color_secondary":"#769f99","color_source":"logo"},
  {"league":"pwhl","team_id":"10","abbr":null,"name":"PWHL Detroit","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#c12e30","color_secondary":"#8f6667","color_source":"logo"},
  {"league":"pwhl","team_id":"11","abbr":null,"name":"PWHL Hamilton","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#5c0a17","color_secondary":"#e2a035","color_source":"logo"},
  {"league":"pwhl","team_id":"12","abbr":null,"name":"PWHL Las Vegas","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#717237","color_secondary":"#dfc287","color_source":"logo"},
  {"league":"pwhl","team_id":"13","abbr":null,"name":"PWHL San Jose","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#f69245","color_secondary":"#7a88a2","color_source":"logo"},
  {"league":"pwhl","team_id":"2","abbr":null,"name":"Minnesota Frost","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#9e7db8","color_secondary":"#262161","color_source":"logo"},
  {"league":"pwhl","team_id":"3","abbr":null,"name":"Montréal Victoire","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#872a36","color_secondary":"#0a2041","color_source":"logo"},
  {"league":"pwhl","team_id":"4","abbr":null,"name":"New York Sirens","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#00b9b3","color_secondary":"#081c3e","color_source":"logo"},
  {"league":"pwhl","team_id":"5","abbr":null,"name":"Ottawa Charge","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#a51d30","color_secondary":"#fbc657","color_source":"logo"},
  {"league":"pwhl","team_id":"6","abbr":null,"name":"Toronto Sceptres","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#061838","color_secondary":"#9c8023","color_source":"logo"},
  {"league":"pwhl","team_id":"8","abbr":null,"name":"Seattle Torrent","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#8cb7c9","color_secondary":"#0a5458","color_source":"logo"},
  {"league":"pwhl","team_id":"9","abbr":null,"name":"Vancouver Goldeneyes","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#10457f","color_secondary":"#ca9351","color_source":"logo"}
] as const satisfies readonly Team[];
