// generated by tools/build-index — do not edit
import type { Team } from "../index.js";
export const teams: readonly Team[] = [
  {"league":"ufl","team_id":"112646","abbr":"DC","name":"DC DEFENDERS","short_name":"DEFENDERS","location":"DC","program":"pro","conference_id":null,"conference":null,"color_primary":"#c8102e","color_secondary":"#ffffff","color_source":"espn"},
  {"league":"ufl","team_id":"112647","abbr":"DAL","name":"Dallas Renegades","short_name":"Renegades","location":"Dallas","program":"pro","conference_id":null,"conference":null,"color_primary":"#69b3e7","color_secondary":"#000000","color_source":"espn"},
  {"league":"ufl","team_id":"112651","abbr":"STL","name":"St. Louis Battlehawks","short_name":"Battlehawks","location":"St. Louis","program":"pro","conference_id":null,"conference":null,"color_primary":"#002677","color_secondary":"#a2aaad","color_source":"espn"},
  {"league":"ufl","team_id":"125957","abbr":null,"name":"Michigan Panthers","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#691c32","color_secondary":"#f4f4f4","color_source":"espn"},
  {"league":"ufl","team_id":"126073","abbr":"BHAM","name":"Birmingham Stallions","short_name":"Stallions","location":"Birmingham","program":"pro","conference_id":null,"conference":null,"color_primary":"#a32035","color_secondary":"#c6b784","color_source":"espn"},
  {"league":"ufl","team_id":"126075","abbr":"HOU","name":"Houston Gamblers","short_name":"Gamblers","location":"Houston","program":"pro","conference_id":null,"conference":null,"color_primary":"#000000","color_secondary":"#e4002b","color_source":"espn"},
  {"league":"ufl","team_id":"126746","abbr":null,"name":"San Antonio Brahmas","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#2e363a","color_secondary":"#fce300","color_source":"espn"},
  {"league":"ufl","team_id":"129043","abbr":null,"name":"Memphis Showboats","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#12284c","color_secondary":"#f0f0f0","color_source":"espn"},
  {"league":"ufl","team_id":"132261","abbr":"CLB","name":"Columbus Aviators","short_name":"Aviators","location":"Columbus","program":"pro","conference_id":null,"conference":null,"color_primary":"#0c2340","color_secondary":"#69b3e7","color_source":"espn"},
  {"league":"ufl","team_id":"132262","abbr":"LOU","name":"Louisville Kings","short_name":"Kings","location":"Louisville","program":"pro","conference_id":null,"conference":null,"color_primary":"#06190a","color_secondary":"#97d700","color_source":"espn"},
  {"league":"ufl","team_id":"132263","abbr":"ORL","name":"Orlando Storm","short_name":"Storm","location":"Orlando","program":"pro","conference_id":null,"conference":null,"color_primary":"#fe5000","color_secondary":"#252a36","color_source":"espn"}
] as const satisfies readonly Team[];
