// generated by tools/build-index — do not edit
import type { Team } from "../index.js";
export const teams: readonly Team[] = [
  {"league":"usfl","team_id":"birmingham-stallions","abbr":null,"name":"Birmingham Stallions","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#a32035","color_secondary":"#ceb795","color_source":"logo"},
  {"league":"usfl","team_id":"houston-gamblers","abbr":null,"name":"Houston Gamblers","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#ea0029","color_secondary":"#000000","color_source":"logo"},
  {"league":"usfl","team_id":"memphis-showboats","abbr":null,"name":"Memphis Showboats","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#12284c","color_secondary":"#ffb71c","color_source":"logo"},
  {"league":"usfl","team_id":"michigan-panthers","abbr":null,"name":"Michigan Panthers","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#702e3e","color_secondary":"#c6b784","color_source":"logo"},
  {"league":"usfl","team_id":"new-jersey-generals","abbr":null,"name":"New Jersey Generals","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#001a41","color_secondary":"#cb9f54","color_source":"logo"},
  {"league":"usfl","team_id":"new-orleans-breakers","abbr":null,"name":"New Orleans Breakers","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#4298cc","color_secondary":"#003595","color_source":"logo"},
  {"league":"usfl","team_id":"philadelphia-stars","abbr":null,"name":"Philadelphia Stars","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#c10230","color_secondary":"#fba02d","color_source":"logo"},
  {"league":"usfl","team_id":"pittsburgh-maulers","abbr":null,"name":"Pittsburgh Maulers","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#ffb71b","color_secondary":"#000000","color_source":"logo"},
  {"league":"usfl","team_id":"tampa-bay-bandits","abbr":null,"name":"Tampa Bay Bandits","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#c10230","color_secondary":"#000000","color_source":"logo"}
] as const satisfies readonly Team[];
