// generated by tools/build-index — do not edit
import type { Team } from "../index.js";
export const teams: readonly Team[] = [
  {"league":"xfl","team_id":"112646","abbr":null,"name":"DC Defenders","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#c8102e","color_secondary":"#a2aaad","color_source":"espn"},
  {"league":"xfl","team_id":"112647","abbr":null,"name":"Arlington Renegades","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#69b3e7","color_secondary":"#ba0c2f","color_source":"espn"},
  {"league":"xfl","team_id":"112648","abbr":null,"name":"Houston Roughnecks","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#0c2340","color_secondary":"#ba0c2f","color_source":"espn"},
  {"league":"xfl","team_id":"112649","abbr":null,"name":"Los Angeles Wildcats","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#c20f2f","color_secondary":"#ef8903","color_source":"logo"},
  {"league":"xfl","team_id":"112650","abbr":null,"name":"New York Guardians","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#111821","color_secondary":"#a6a7a9","color_source":"logo"},
  {"league":"xfl","team_id":"112651","abbr":null,"name":"St. Louis Battlehawks","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#002677","color_secondary":"#a2aaad","color_source":"espn"},
  {"league":"xfl","team_id":"112652","abbr":null,"name":"Seattle Sea Dragons","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#3a9d2f","color_secondary":"#4c4034","color_source":"logo"},
  {"league":"xfl","team_id":"112653","abbr":null,"name":"Tampa Bay Vipers","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#00833e","color_secondary":"#04301e","color_source":"logo"},
  {"league":"xfl","team_id":"126746","abbr":null,"name":"San Antonio Brahmas","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#2e363a","color_secondary":"#a2aaad","color_source":"espn"},
  {"league":"xfl","team_id":"126747","abbr":null,"name":"Vegas Vipers","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#e10600","color_secondary":"#373a36","color_source":"espn"},
  {"league":"xfl","team_id":"126748","abbr":null,"name":"Orlando Guardians","short_name":null,"location":null,"program":"pro","conference_id":null,"conference":null,"color_primary":"#1a2b1e","color_secondary":"#a3a6ad","color_source":"espn"}
] as const satisfies readonly Team[];
