import type { Color } from "../scene.js";

export const BASKETBALL_FEATURES = [
  "half_court",
  "court_apron",
  "center_circle_outline",
  "center_circle_fill",
  "division_line",
  "endline",
  "sideline",
  "two_point_range",
  "three_point_line",
  "painted_area",
  "free_throw_lane_boundary",
  "lane_space_mark",
  "free_throw_circle_fill",
  "free_throw_circle",
  "free_throw_circle_dash",
  "restricted_arc",
  "lower_defensive_box_mark",
  "inbounding_line",
  "substitution_line",
  "team_bench_line",
  "backboard",
  "basket_ring",
  "net",
] as const;
export type BasketballFeature = (typeof BASKETBALL_FEATURES)[number];

/** Verbatim keys of the `switch(tolower(display_range))` in sportyR `geom_basketball()` (49). */
export const BASKETBALL_DISPLAY_RANGES = [
  "full",
  "in_bounds_only",
  "in bounds only",
  "offense",
  "offence",
  "offensivehalfcourt",
  "offensive_half_court",
  "offensive half court",
  "defense",
  "defence",
  "defensivehalfcourt",
  "defensive_half_court",
  "defensive half court",
  "offensivekey",
  "offensive_key",
  "offensive key",
  "attackingkey",
  "attacking_key",
  "attacking key",
  "defensivekey",
  "defensive_key",
  "defensive key",
  "defendingkey",
  "defending_key",
  "defending key",
  "offensivepaint",
  "offensive_paint",
  "offensive paint",
  "attackingpaint",
  "attacking_paint",
  "attacking paint",
  "offensivelane",
  "offensive_lane",
  "offensive lane",
  "attackinglane",
  "attacking_lane",
  "attacking lane",
  "defensivepaint",
  "defensive_paint",
  "defensive paint",
  "defendingpaint",
  "defending_paint",
  "defending paint",
  "defensivelane",
  "defensive_lane",
  "defensive lane",
  "defendinglane",
  "defending_lane",
  "defending lane",
] as const;
export type BasketballDisplayRange = (typeof BASKETBALL_DISPLAY_RANGES)[number];

const SURFACE = "#d2ab6f";
const LINE = "#000000";

/** Defaults of `basketball_features_set_colors()`, re-keyed to feature names. */
export const BASKETBALL_DEFAULT_COLORS: Readonly<Record<BasketballFeature | "plot_background", Color>> = {
  plot_background: "#ffffff00",
  half_court: SURFACE,
  court_apron: SURFACE,
  center_circle_outline: LINE,
  center_circle_fill: SURFACE,
  division_line: LINE,
  endline: LINE,
  sideline: LINE,
  two_point_range: SURFACE,
  three_point_line: LINE,
  painted_area: SURFACE,
  free_throw_lane_boundary: LINE, // R: lane_boundary
  lane_space_mark: LINE,
  free_throw_circle_fill: SURFACE,
  free_throw_circle: LINE, // R: free_throw_circle_outline
  free_throw_circle_dash: LINE,
  restricted_arc: LINE,
  lower_defensive_box_mark: LINE, // R: baseline_/lane_lower_defensive_box
  inbounding_line: LINE,
  substitution_line: LINE,
  team_bench_line: LINE,
  backboard: LINE,
  basket_ring: "#f55b33",
  net: "#ffffff",
};
