import type { Color } from "../scene.js";

/** One name per sportyR `lacrosse_*` builder (prefix dropped), in draw order, as used in `PolygonFeature.name` (33; R defines `lacrosse_referee_crease` twice, identically). */
export const LACROSSE_FEATURES = [
  "field_apron",
  "defensive_zone",
  "neutral_zone",
  "offensive_zone",
  "referee_crease_fill",
  "sideline",
  "end_line",
  "change_area_outline",
  "change_area_fill",
  "center_line",
  "player_bench_area_fill",
  "player_bench_outline",
  "penalty_box_fill",
  "penalty_box_outline",
  "off_field_officials_box",
  "boards",
  "wing_line",
  "restraining_line",
  "defensive_area_line",
  "referee_crease",
  "center_circle",
  "goal_circle_fill",
  "goal_circle",
  "goal_arc",
  "goal_fan",
  "goal_fan_hash_mark",
  "goal_mouth",
  "goal_mouth_hash_mark",
  "below_goal_marking",
  "goal_net",
  "goal_frame",
  "goal_line",
  "face_off_marker",
] as const;
export type LacrosseFeature = (typeof LACROSSE_FEATURES)[number];

/** Verbatim keys of the `switch(tolower(display_range))` in sportyR `geom_lacrosse()` (13). */
export const LACROSSE_DISPLAY_RANGES = [
  "full",
  "in_bounds_only",
  "in bounds only",
  "offense",
  "offence",
  "offensivehalffield",
  "offensive_half_field",
  "offensive half field",
  "defense",
  "defence",
  "defensivehalffield",
  "defensive_half_field",
  "defensive half field",
] as const;
export type LacrosseDisplayRange = (typeof LACROSSE_DISPLAY_RANGES)[number];

/** The 35 argument names of `lacrosse_features_set_colors()`, in R's declaration order (colour keys are NOT feature names). */
export const LACROSSE_COLOR_KEYS = [
  "plot_background",
  "field_apron",
  "defensive_zone",
  "neutral_zone",
  "offensive_zone",
  "team_a_bench",
  "team_b_bench",
  "team_a_penalty_box",
  "team_b_penalty_box",
  "off_field_officials_box",
  "boards",
  "end_line",
  "sideline",
  "center_line",
  "wing_line",
  "restraining_line",
  "defensive_area_line",
  "goal_line",
  "referee_crease",
  "referee_crease_fill",
  "goal_circle",
  "goal_circle_fill",
  "goal_arc",
  "goal_fan",
  "goal_fan_hash_mark",
  "goal_mouth_hash_mark",
  "goal_mouth",
  "below_goal_marking",
  "goal_frame",
  "goal_net",
  "center_circle",
  "center_face_off_marker",
  "corner_face_off_marker",
  "change_area_outline",
  "change_area_fill",
] as const;
export type LacrosseColorKey = (typeof LACROSSE_COLOR_KEYS)[number];

/** Defaults of `lacrosse_features_set_colors()` (R's plot_background default is NULL; transparent here). */
export const LACROSSE_DEFAULT_COLORS: Readonly<Record<LacrosseColorKey, Color>> = {
  plot_background: "#ffffff00",
  field_apron: "#195f0c",
  defensive_zone: "#195f0c",
  neutral_zone: "#195f0c",
  offensive_zone: "#195f0c",
  team_a_bench: "#a5acaf4d",
  team_b_bench: "#a5acaf4d",
  team_a_penalty_box: "#a5acaf4d",
  team_b_penalty_box: "#a5acaf4d",
  off_field_officials_box: "#a5acaf",
  boards: "#ffa500",
  end_line: "#ffffff",
  sideline: "#ffffff",
  center_line: "#ffffff",
  wing_line: "#ffffff",
  restraining_line: "#ffffff",
  defensive_area_line: "#ffffff",
  goal_line: "#ffffff",
  referee_crease: "#ffffff",
  referee_crease_fill: "#195f0c",
  goal_circle: "#ffffff",
  goal_circle_fill: "#195f0c",
  goal_arc: "#ffffff",
  goal_fan: "#ffffff",
  goal_fan_hash_mark: "#ffffff",
  goal_mouth_hash_mark: "#ffffff",
  goal_mouth: "#ffffff",
  below_goal_marking: "#ffffff",
  goal_frame: "#ffa500",
  goal_net: "#a5acaf4d",
  center_circle: "#ffffff",
  center_face_off_marker: "#ffffff",
  corner_face_off_marker: "#ffffff",
  change_area_outline: "#ffffff",
  change_area_fill: "#195f0c",
};
