// generated by tools/build-index — do not edit
import type { StoredMark } from "../index.js";
export const marks: readonly StoredMark[] = [
  {"team_id":"720","mark_type":"logo","variant":"crop_64px","valid_from":2019,"valid_to":2019,"source":"aaf-strip-crop","first_seen":"2026-09-30","sha256":"0369cfbe77363cc331303cd0c3663586596dbb9e0164d779612dd7cd4cff0b19","ext":"png","width":62,"height":64,"source_rank":6},
  {"team_id":"722","mark_type":"logo","variant":"crop_64px","valid_from":2019,"valid_to":2019,"source":"aaf-strip-crop","first_seen":"2026-09-30","sha256":"1afbb80e2751dab8cd8466103ac0c7dedee0942df7c8a15d68135ac9bfc85841","ext":"png","width":88,"height":64,"source_rank":6},
  {"team_id":"724","mark_type":"logo","variant":"crop_64px","valid_from":2019,"valid_to":2019,"source":"aaf-strip-crop","first_seen":"2026-09-30","sha256":"838c0d1abc0b04c8b47cf79f1b5b0a4b22ed2da22930d8f2fb2b44521fdcdb6a","ext":"png","width":75,"height":64,"source_rank":6},
  {"team_id":"725","mark_type":"logo","variant":"crop_64px","valid_from":2019,"valid_to":2019,"source":"aaf-strip-crop","first_seen":"2026-09-30","sha256":"ba59450d62ced0db7bb82e7cea40594b7b1e6b879ec66c650645713cfdbbfa20","ext":"png","width":77,"height":64,"source_rank":6},
  {"team_id":"721","mark_type":"logo","variant":"crop_64px","valid_from":2019,"valid_to":2019,"source":"aaf-strip-crop","first_seen":"2026-09-30","sha256":"be42a8e11eb375961dc538279643334234970054f57fe44b889f60b093e76cd0","ext":"png","width":72,"height":64,"source_rank":6},
  {"team_id":"719","mark_type":"logo","variant":"crop_64px","valid_from":2019,"valid_to":2019,"source":"aaf-strip-crop","first_seen":"2026-09-30","sha256":"d4bdb2c1c7fc6e49d8a3815ef4908b119b5d143300e5b8f2208696c67f2bfe9c","ext":"png","width":74,"height":64,"source_rank":6},
  {"team_id":"723","mark_type":"logo","variant":"crop_64px","valid_from":2019,"valid_to":2019,"source":"aaf-strip-crop","first_seen":"2026-09-30","sha256":"fe04a4e83c568ebb5acbdd0374440aeaad10f3f0791f0c63e6ed337232ca9940","ext":"png","width":73,"height":64,"source_rank":6},
  {"team_id":"726","mark_type":"logo","variant":"crop_64px","valid_from":2019,"valid_to":2019,"source":"aaf-strip-crop","first_seen":"2026-09-30","sha256":"ff7d80caaa67b931b0095435faf2f6fe934ed3f9c97940488460cf73b504e7d9","ext":"png","width":55,"height":64,"source_rank":6}
] as const satisfies readonly StoredMark[];
