type Leagues = Record<string, Record<string, unknown>>;
const isNumArr = (v: unknown): v is number[] => Array.isArray(v) && v.every((x) => typeof x === "number");
const isBoolArr = (v: unknown): v is boolean[] => Array.isArray(v) && v.every((x) => typeof x === "boolean");
const isStrArr = (v: unknown): v is string[] => Array.isArray(v) && v.every((x) => typeof x === "string");
const isNum2d = (v: unknown): v is number[][] => Array.isArray(v) && v.length > 0 && v.every(isNumArr);

/** The field's type across every league: a field that is a number in one league and number[] in another is `readonly number[]`. */
export function inferFieldType(field: string, leagues: Leagues): string {
  const vals = Object.values(leagues)
    .map((l) => l[field])
    .filter((v) => v !== undefined);
  if (vals.some(isNum2d) && vals.every((v) => isNum2d(v) || isNumArr(v)))
    return "readonly (readonly number[])[]";
  if (vals.some(Array.isArray)) {
    if (vals.every((v) => isNumArr(v) || typeof v === "number")) return "readonly number[]";
    if (vals.every((v) => isBoolArr(v) || typeof v === "boolean")) return "readonly boolean[]";
    if (vals.every((v) => isStrArr(v) || typeof v === "string")) return "readonly string[]";
    throw new Error(`${field}: mixed array types`);
  }
  if (vals.every((v) => typeof v === "number")) return "number";
  if (vals.every((v) => typeof v === "boolean")) return "boolean";
  if (vals.every((v) => typeof v === "string")) {
    const u = [...new Set(vals as string[])];
    return field.endsWith("_units") ? u.map((s) => JSON.stringify(s)).join(" | ") : "string";
  }
  throw new Error(`${field}: mixed scalar types`);
}
const pascal = (s: string) => s.replace(/(^|_)(\w)/g, (_, __, c: string) => c.toUpperCase());

export function emitSport(sport: string, leagues: Leagues): string {
  const P = pascal(sport);
  const names = Object.keys(leagues).sort();
  const fields = [...new Set(names.flatMap((l) => Object.keys(leagues[l] ?? {})))].sort();
  const types = Object.fromEntries(fields.map((f) => [f, inferFieldType(f, leagues)]));
  const norm = (f: string, v: unknown) => {
    const t = types[f] ?? "";
    if (v === undefined) return undefined;
    if (t.startsWith("readonly") && !Array.isArray(v)) return [v];
    if (t === "readonly (readonly number[])[]" && isNumArr(v)) return [v];
    return v;
  };
  const specs = Object.fromEntries(
    names.map((l) => [
      l,
      Object.fromEntries(fields.map((f) => [f, norm(f, leagues[l]?.[f])]).filter(([, v]) => v !== undefined)),
    ]),
  );
  const optional = (f: string) => (names.some((l) => leagues[l]?.[f] === undefined) ? "?" : "");
  return `// generated by tools/codegen — do not edit (source: packages/sporty/data/surface-dimensions.json)
export const ${sport.toUpperCase()}_LEAGUES = ${JSON.stringify(names)} as const;
export type ${P}League = (typeof ${sport.toUpperCase()}_LEAGUES)[number];
export interface ${P}Params {
${fields.map((f) => `  ${f}${optional(f)}: ${types[f]};`).join("\n")}
}
export type ${P}Loosen<T> = T extends readonly (readonly number[])[] ? readonly number[] | readonly (readonly number[])[] : T extends readonly number[] ? number | readonly number[] : T extends readonly boolean[] ? boolean | readonly boolean[] : T extends readonly string[] ? string | readonly string[] : T;
export type ${P}ParamUpdates = { [K in keyof ${P}Params]?: ${P}Loosen<${P}Params[K]> };
export const ${sport.toUpperCase()}_SPECS: Readonly<Record<${P}League, ${P}Params>> = ${JSON.stringify(specs)} as const;
`;
}
