// generated by tools/codegen — do not edit (source: packages/sporty/data/surface-dimensions.json)
export const CURLING_LEAGUES = ["curling canada","custom","wcf"] as const;
export type CurlingLeague = (typeof CURLING_LEAGUES)[number];
export interface CurlingParams {
  apron_along_side: number;
  apron_behind_back: number;
  back_line_thickness: number;
  back_line_to_tee_line: number;
  button_radius: number;
  centre_line_extension: number;
  centre_line_thickness: number;
  courtesy_line_length: number;
  courtesy_line_thickness: number;
  courtesy_line_to_hog_line: number;
  hack_foothold_depth: number;
  hack_foothold_gap: number;
  hack_foothold_width: number;
  hack_line_thickness: number;
  hog_line_thickness: number;
  hog_line_to_tee_line: number;
  house_ring_radii: readonly number[];
  sheet_length: number;
  sheet_units: "" | "ft";
  sheet_width: number;
  tee_line_thickness: number;
  tee_line_to_center: number;
}
type Loosen<T> = T extends readonly (readonly number[])[] ? readonly number[] | readonly (readonly number[])[] : T extends readonly number[] ? number | readonly number[] : T extends readonly boolean[] ? boolean | readonly boolean[] : T extends readonly string[] ? string | readonly string[] : T;
export type CurlingParamUpdates = { [K in keyof CurlingParams]?: Loosen<CurlingParams[K]> };
export const CURLING_SPECS: Readonly<Record<CurlingLeague, CurlingParams>> = {"curling canada":{"apron_along_side":1.5,"apron_behind_back":1.5,"back_line_thickness":0.0417,"back_line_to_tee_line":6,"button_radius":0.5,"centre_line_extension":12,"centre_line_thickness":0.0417,"courtesy_line_length":0.5,"courtesy_line_thickness":0.0417,"courtesy_line_to_hog_line":4,"hack_foothold_depth":0.6667,"hack_foothold_gap":0.5,"hack_foothold_width":0.5,"hack_line_thickness":0.0417,"hog_line_thickness":0.3333,"hog_line_to_tee_line":21,"house_ring_radii":[6,4,2],"sheet_length":150,"sheet_units":"ft","sheet_width":15.5833,"tee_line_thickness":0.0417,"tee_line_to_center":57},"custom":{"apron_along_side":0,"apron_behind_back":0,"back_line_thickness":0,"back_line_to_tee_line":0,"button_radius":0,"centre_line_extension":0,"centre_line_thickness":0,"courtesy_line_length":0,"courtesy_line_thickness":0,"courtesy_line_to_hog_line":0,"hack_foothold_depth":0,"hack_foothold_gap":0,"hack_foothold_width":0,"hack_line_thickness":0,"hog_line_thickness":0,"hog_line_to_tee_line":0,"house_ring_radii":[0,0,0],"sheet_length":0,"sheet_units":"","sheet_width":0,"tee_line_thickness":0,"tee_line_to_center":0},"wcf":{"apron_along_side":1.5,"apron_behind_back":1.5,"back_line_thickness":0.0417,"back_line_to_tee_line":6,"button_radius":0.5,"centre_line_extension":12,"centre_line_thickness":0.0417,"courtesy_line_length":0.5,"courtesy_line_thickness":0.0417,"courtesy_line_to_hog_line":4,"hack_foothold_depth":0.6667,"hack_foothold_gap":0.5,"hack_foothold_width":0.5,"hack_line_thickness":0.0417,"hog_line_thickness":0.3333,"hog_line_to_tee_line":21,"house_ring_radii":[6,4,2],"sheet_length":150,"sheet_units":"ft","sheet_width":15.5833,"tee_line_thickness":0.0417,"tee_line_to_center":57}} as const;
