// generated by tools/codegen — do not edit (source: packages/sporty/data/surface-dimensions.json)
export const TENNIS_LEAGUES = ["atp","custom","ita","itf","ncaa","usta","wta"] as const;
export type TennisLeague = (typeof TENNIS_LEAGUES)[number];
export interface TennisParams {
  backstop_distance: number;
  center_mark_length: number;
  court_length: number;
  court_units: "" | "ft";
  doubles_width: number;
  line_thickness: number;
  net_length: number;
  serviceline_distance: number;
  sidestop_distance: number;
  singles_width: number;
}
export type TennisLoosen<T> = T extends readonly (readonly number[])[] ? readonly number[] | readonly (readonly number[])[] : T extends readonly number[] ? number | readonly number[] : T extends readonly boolean[] ? boolean | readonly boolean[] : T extends readonly string[] ? string | readonly string[] : T;
export type TennisParamUpdates = { [K in keyof TennisParams]?: TennisLoosen<TennisParams[K]> };
export const TENNIS_SPECS: Readonly<Record<TennisLeague, TennisParams>> = {"atp":{"backstop_distance":21,"center_mark_length":0.3333,"court_length":78,"court_units":"ft","doubles_width":36,"line_thickness":0.1667,"net_length":42,"serviceline_distance":21,"sidestop_distance":12,"singles_width":27},"custom":{"backstop_distance":0,"center_mark_length":0,"court_length":0,"court_units":"","doubles_width":0,"line_thickness":0,"net_length":0,"serviceline_distance":0,"sidestop_distance":0,"singles_width":0},"ita":{"backstop_distance":21,"center_mark_length":0.3333,"court_length":78,"court_units":"ft","doubles_width":36,"line_thickness":0.1667,"net_length":42,"serviceline_distance":21,"sidestop_distance":12,"singles_width":27},"itf":{"backstop_distance":21,"center_mark_length":0.3333,"court_length":78,"court_units":"ft","doubles_width":36,"line_thickness":0.1667,"net_length":42,"serviceline_distance":21,"sidestop_distance":12,"singles_width":27},"ncaa":{"backstop_distance":21,"center_mark_length":0.3333,"court_length":78,"court_units":"ft","doubles_width":36,"line_thickness":0.1667,"net_length":42,"serviceline_distance":21,"sidestop_distance":12,"singles_width":27},"usta":{"backstop_distance":21,"center_mark_length":0.3333,"court_length":78,"court_units":"ft","doubles_width":36,"line_thickness":0.1667,"net_length":42,"serviceline_distance":21,"sidestop_distance":12,"singles_width":27},"wta":{"backstop_distance":21,"center_mark_length":0.3333,"court_length":78,"court_units":"ft","doubles_width":36,"line_thickness":0.1667,"net_length":42,"serviceline_distance":21,"sidestop_distance":12,"singles_width":27}} as const;
