// generated by tools/codegen — do not edit (source: packages/sporty/data/surface-dimensions.json)
export const VOLLEYBALL_LEAGUES = ["custom","fivb","ncaa","usa volleyball"] as const;
export type VolleyballLeague = (typeof VOLLEYBALL_LEAGUES)[number];
export interface VolleyballParams {
  attack_line_edge_to_center_line: number;
  court_apron_end_line: number;
  court_apron_sideline: number;
  court_length: number;
  court_units: "m";
  court_width: number;
  free_zone_end_line: number;
  free_zone_sideline: number;
  line_thickness: number;
  service_zone_mark_length: number;
  service_zone_mark_to_end_line: number;
  substitution_zone_dash_breaks: number;
  substitution_zone_dash_length: number;
  substitution_zone_rep_pattern: number;
}
type Loosen<T> = T extends readonly (readonly number[])[] ? readonly number[] | readonly (readonly number[])[] : T extends readonly number[] ? number | readonly number[] : T extends readonly boolean[] ? boolean | readonly boolean[] : T extends readonly string[] ? string | readonly string[] : T;
export type VolleyballParamUpdates = { [K in keyof VolleyballParams]?: Loosen<VolleyballParams[K]> };
export const VOLLEYBALL_SPECS: Readonly<Record<VolleyballLeague, VolleyballParams>> = {"custom":{"attack_line_edge_to_center_line":0,"court_apron_end_line":0,"court_apron_sideline":0.5,"court_length":0,"court_units":"m","court_width":0,"free_zone_end_line":0,"free_zone_sideline":0,"line_thickness":0,"service_zone_mark_length":0,"service_zone_mark_to_end_line":0,"substitution_zone_dash_breaks":0,"substitution_zone_dash_length":0,"substitution_zone_rep_pattern":0},"fivb":{"attack_line_edge_to_center_line":3,"court_apron_end_line":2,"court_apron_sideline":1.5,"court_length":18,"court_units":"m","court_width":9,"free_zone_end_line":6.5,"free_zone_sideline":5,"line_thickness":0.05,"service_zone_mark_length":0.15,"service_zone_mark_to_end_line":0.2,"substitution_zone_dash_breaks":0.2,"substitution_zone_dash_length":0.15,"substitution_zone_rep_pattern":5},"ncaa":{"attack_line_edge_to_center_line":3,"court_apron_end_line":2,"court_apron_sideline":1.5,"court_length":18,"court_units":"m","court_width":9,"free_zone_end_line":4.5,"free_zone_sideline":3,"line_thickness":0.05,"service_zone_mark_length":0.15,"service_zone_mark_to_end_line":0.2,"substitution_zone_dash_breaks":0.2,"substitution_zone_dash_length":0.15,"substitution_zone_rep_pattern":5},"usa volleyball":{"attack_line_edge_to_center_line":3,"court_apron_end_line":2,"court_apron_sideline":1.5,"court_length":18,"court_units":"m","court_width":9,"free_zone_end_line":4.5,"free_zone_sideline":3,"line_thickness":0.05,"service_zone_mark_length":0.15,"service_zone_mark_to_end_line":0.2,"substitution_zone_dash_breaks":0.2,"substitution_zone_dash_length":0.15,"substitution_zone_rep_pattern":5}} as const;
