import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// One generated sidebar. docusaurus.config.ts (sidebarItemsGenerator) adds the Notebooks category from
// plugins/notebooks.ts, after the Gallery: a sidebars file may export nothing but sidebars.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
