import { expect, test } from "vitest";
import { emitConstModule, rankMarks } from "./emit.js";

test("emitConstModule writes a header and as-const data", () => {
  const src = emitConstModule("teams", "Team", [{ league: "nfl", team_id: "12", abbr: "KC" }]);
  expect(src.startsWith("// generated by tools/build-index — do not edit")).toBe(true);
  expect(src).toContain("as const satisfies readonly Team[]");
  expect(src).toContain('"team_id":"12"');
});

test("rankMarks orders by source_rank, open-ended first, valid_to desc, first_seen desc, valid_from desc, sha", () => {
  const rows = rankMarks([
    {
      team_id: "1",
      mark_type: "logo",
      variant: "default",
      valid_from: 2000,
      valid_to: 2010,
      source: "espn",
      first_seen: "2024-01-01",
      sha256: "b",
      ext: "png",
      width: null,
      height: null,
      archive_url: "u1",
    },
    {
      team_id: "1",
      mark_type: "logo",
      variant: "default",
      valid_from: 2011,
      valid_to: null,
      source: "espn",
      first_seen: "2024-01-01",
      sha256: "a",
      ext: "png",
      width: null,
      height: null,
      archive_url: "u2",
    },
    {
      team_id: "1",
      mark_type: "logo",
      variant: "default",
      valid_from: null,
      valid_to: null,
      source: "wayback",
      first_seen: "2024-01-01",
      sha256: "c",
      ext: "png",
      width: null,
      height: null,
      archive_url: "u3",
    },
  ]);
  expect(rows.map((r) => r.archive_url)).toEqual(["u2", "u1", "u3"]);
  expect(rows[0]?.source_rank).toBe(0);
  expect(rows[2]?.source_rank).toBe(4);
});

test("leagueFirstSeason: only whole-history id systems that close a range set a floor", async () => {
  const { leagueFirstSeason } = await import("./emit.js");
  const a = (id_system: string, valid_from: number | null, valid_to: number | null) => ({
    id_system,
    valid_from,
    valid_to,
  });
  expect(leagueFirstSeason([a("nflverse", 1980, 1996), a("espn", 2026, null)])).toBeNull();
  expect(leagueFirstSeason([a("bref", 1920, 1930), a("bref", 1931, null), a("nflverse", 1900, 1910)])).toBe(
    1920,
  );
  expect(leagueFirstSeason([a("bref", 1950, null)])).toBeNull();
});
