import type { MarkRow } from "../../packages/sdvplot/src/data/index.js";
import { SOURCE_RANK, compareMarks } from "../../packages/sdvplot/src/rank.js";

export const HEADER = "// generated by tools/build-index — do not edit\n";
/** Content-addressed archive (DO Spaces): `<base>/<sha[:2]>/<sha>.<ext>`, the layout of Python's `_images.mark_file`. */
export const ARCHIVE_BASE = "https://sdv.nyc3.cdn.digitaloceanspaces.com/assets/public/sha256";
export const archiveUrl = (sha256: string, ext: string): string =>
  `${ARCHIVE_BASE}/${sha256.slice(0, 2)}/${sha256}.${ext}`;

export function emitConstModule(
  name: string,
  type: string,
  rows: readonly unknown[],
  importFrom = "../index.js",
): string {
  const body = rows.map((r) => JSON.stringify(r)).join(",\n  ");
  return `${HEADER}import type { ${type} } from "${importFrom}";\nexport const ${name}: readonly ${type}[] = [\n  ${body}\n] as const satisfies readonly ${type}[];\n`;
}

/** A shard row: `archive_url` is never stored — the loader derives it from sha256 + ext (`archiveUrl`). */
export type StoredMark = Omit<MarkRow, "archive_url">;
export type RawMark = Omit<StoredMark, "source_rank">;
/** Python `_ranked`: sort by source_rank asc, open-ended (valid_to null) first, valid_to desc, first_seen desc, valid_from desc, sha256 asc; nulls last. */
export function rankMarks(rows: readonly RawMark[]): StoredMark[] {
  return rows.map((r) => ({ ...r, source_rank: SOURCE_RANK[r.source] ?? 5 })).sort(compareMarks);
}

/** Id systems whose dated aliases cover a league's whole history (Python `_index._HISTORY_SYSTEMS`); a curated relocation (nflverse OAK, NHL WIN) dates one team, not the league. */
export const HISTORY_SYSTEMS: readonly string[] = ["bref", "sportsipy", "mlbstats", "espn_abbr"];

/** A league's own first season: set only when a history-system alias closes a range; then the min over that league's history-system aliases. Else null (index floor applies). */
export function leagueFirstSeason(
  aliases: readonly { id_system: string; valid_from: number | null; valid_to: number | null }[],
): number | null {
  const h = aliases.filter((a) => HISTORY_SYSTEMS.includes(a.id_system));
  if (!h.some((a) => a.valid_to !== null)) return null;
  const xs = h.flatMap((a) => [a.valid_from, a.valid_to]).filter((x): x is number => x !== null);
  return xs.length ? Math.min(...xs) : null;
}
