import ts from "typescript";
import type { ExampleEntry, ExampleMeta } from "../src/contract.js";

/** One file the generator writes, relative to `examples/`. */
export interface GenFile {
  readonly path: string;
  readonly text: string;
}

const parse = (source: string, fileName: string): ts.SourceFile =>
  ts.createSourceFile(
    fileName,
    source,
    ts.ScriptTarget.Latest,
    true,
    fileName.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
  );
const exported = (s: ts.Statement): boolean =>
  ts.canHaveModifiers(s) && (ts.getModifiers(s) ?? []).some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
const isMeta = (s: ts.Statement): s is ts.VariableStatement =>
  ts.isVariableStatement(s) &&
  exported(s) &&
  s.declarationList.declarations.some((d) => ts.isIdentifier(d.name) && d.name.text === "meta");
const isContractImport = (s: ts.Statement): boolean =>
  ts.isImportDeclaration(s) &&
  ts.isStringLiteral(s.moduleSpecifier) &&
  s.moduleSpecifier.text.endsWith("/contract.js");

/** `export const meta = { title: "…", tags: ["…"] } satisfies ExampleMeta;`, read from the AST: nothing is executed. */
export function metaOf(source: string, fileName: string): ExampleMeta {
  const st = parse(source, fileName).statements.find(isMeta);
  let init = st?.declarationList.declarations[0]?.initializer;
  while (
    init &&
    (ts.isSatisfiesExpression(init) || ts.isAsExpression(init) || ts.isParenthesizedExpression(init))
  )
    init = init.expression;
  if (!init || !ts.isObjectLiteralExpression(init))
    throw new Error(`${fileName}: needs \`export const meta = { title, tags } satisfies ExampleMeta\``);
  let title: string | undefined;
  let tags: string[] | undefined;
  for (const p of init.properties) {
    if (!ts.isPropertyAssignment(p) || !ts.isIdentifier(p.name)) continue;
    if (p.name.text === "title" && ts.isStringLiteralLike(p.initializer)) title = p.initializer.text;
    if (p.name.text === "tags" && ts.isArrayLiteralExpression(p.initializer))
      tags = p.initializer.elements.map((e) => {
        if (!ts.isStringLiteralLike(e)) throw new Error(`${fileName}: meta.tags must be string literals`);
        return e.text;
      });
  }
  if (title === undefined || tags === undefined)
    throw new Error(`${fileName}: meta needs a literal string \`title\` and a literal string[] \`tags\``);
  return { title, tags };
}

/**
 * The code a reader sees: the module minus `meta`, minus the contract import, with `export default X;` shown as
 * `X;`. Cuts are AST positions on the original text, so comments and formatting survive.
 */
export function codeOf(source: string, fileName: string): string {
  const sf = parse(source, fileName);
  const cuts: [number, number][] = [];
  let hasDefault = false;
  for (const s of sf.statements) {
    if (isMeta(s) || isContractImport(s)) cuts.push([s.getStart(sf), s.getEnd()]);
    else if (ts.isExportAssignment(s) && !s.isExportEquals) {
      cuts.push([s.getStart(sf), s.expression.getStart(sf)]);
      hasDefault = true;
    }
  }
  if (!hasDefault) throw new Error(`${fileName}: an example's default export is its output; there is none`);
  let out = source;
  for (const [a, b] of cuts.sort((x, y) => y[0] - x[0])) out = out.slice(0, a) + out.slice(b);
  out = out.replace(/^\/\/ generated by examples\/scripts\/gen\.ts.*\n/, "");
  return `${out.replace(/\n{3,}/g, "\n\n").trim()}\n`;
}

/** One fenced block under an `@example` tag. */
export interface DocExample {
  readonly symbol: string;
  readonly lang: "ts" | "tsx";
  readonly code: string;
}
// A doc comment that cannot contain "*/", then the exported declaration it documents.
const DOC =
  /\/\*\*((?:[^*]|\*(?!\/))*)\*\/\s*export\s+(?:declare\s+)?(?:default\s+)?(?:async\s+)?(?:function\*?|const|let|class|interface|type|enum)\s+([A-Za-z_$][\w$]*)/g;

/** Every fenced block under an `@example` tag of an exported declaration, in source order. */
export function extractDocExamples(source: string, fileName: string): DocExample[] {
  const found: DocExample[] = [];
  for (const m of source.matchAll(DOC)) {
    const symbol = m[2] ?? "";
    const lines = (m[1] ?? "").split("\n").map((l) => l.replace(/^\s*\* ?/, ""));
    for (let i = 0; i < lines.length; i++) {
      if (!/^@example\b/.test(lines[i]?.trim() ?? "")) continue;
      const open = lines.findIndex((l, j) => j > i && /^```/.test(l.trim()));
      const fence = open < 0 ? null : /^```(\w*)\s*$/.exec(lines[open]?.trim() ?? "");
      if (!fence || lines.slice(i + 1, open).some((l) => l.trim().startsWith("@")))
        throw new Error(`${fileName}: @example on ${symbol} must be a fenced \`\`\`ts block`);
      const close = lines.findIndex((l, j) => j > open && l.trim() === "```");
      if (close < 0) throw new Error(`${fileName}: unclosed @example fence on ${symbol}`);
      const lang = fence[1] === "tsx" || fence[1] === "jsx" ? "tsx" : "ts";
      found.push({ symbol, lang, code: `${lines.slice(open + 1, close).join("\n")}\n` });
      i = close;
    }
  }
  return found;
}

/** A docstring example as an example module: its imports, `meta`, then the body with the last expression exported. */
export function docModule(o: DocExample & { readonly from: string; readonly contract: string }): string {
  const sf = parse(o.code, `example.${o.lang}`);
  const firstBody = sf.statements.findIndex((s) => !ts.isImportDeclaration(s));
  const body = firstBody < 0 ? [] : sf.statements.slice(firstBody);
  if (body.some((s) => ts.isImportDeclaration(s)))
    throw new Error(`${o.from}: @example on ${o.symbol} must put its imports first`);
  const last = body.at(-1);
  if (last === undefined || !ts.isExpressionStatement(last))
    throw new Error(`${o.from}: @example on ${o.symbol} must end with the expression it shows`);
  const imports = sf.statements.slice(0, firstBody).map((s) => s.getText(sf));
  const start = body[0]?.getStart(sf) ?? 0;
  const at = last.getStart(sf);
  const meta = `{ title: ${JSON.stringify(o.symbol)}, tags: ${JSON.stringify(["docstring", o.symbol])} }`;
  return [
    `// generated by examples/scripts/gen.ts from ${o.from} (@example on ${o.symbol}) - do not edit`,
    ...imports,
    `import type { ExampleMeta } from ${JSON.stringify(o.contract)};`,
    "",
    `export const meta = ${meta} satisfies ExampleMeta;`,
    "",
    `${o.code.slice(start, at)}export default ${o.code.slice(at).trimEnd()}`,
    "",
  ].join("\n");
}

/**
 * Gallery families: one generated example per member. test/completeness.test.ts fails when a package adds a member.
 * `custom` leagues are templates, not surfaces: with no `updates` basketball and football draw NaN coordinates.
 */
export const THEMES = [
  "sdv",
  "sdvTeam",
  "almanac",
  "athletic",
  "booktabs",
  "broadsheet",
  "brutalist",
  "drench",
  "gtutils",
  "kenpom",
  "midnight",
  "ncaa",
  "pl",
  "savant",
  "scoreboard",
  "sofa",
  "swiss",
  "terminal",
  "tier",
  "tufte",
] as const;
const THEME_OPTIONS: Readonly<Record<string, string>> = {
  sdvTeam: `, { options: { league: "nfl", team: "KC" } }`,
};
export const SURFACE_LEAGUES = {
  basketball: ["fiba", "nba", "nba g league", "ncaa", "nfhs", "wnba"],
  hockey: ["ahl", "echl", "iihf", "ncaa", "nhl", "nwhl", "ohl", "phf", "pwhl", "qmjhl", "ushl"],
  football: ["cfl", "ncaa", "nfhs11", "nfhs6", "nfhs8", "nfhs9", "nfl"],
} as const;
const slug = (s: string): string => s.replace(/[^A-Za-z0-9]+/g, "-");
const HEADER = "// generated by examples/scripts/gen.ts (a gallery family) - do not edit";
const CONTRACT = `import type { ExampleMeta } from "../../../contract.js";`;
const q = (v: unknown): string => JSON.stringify(v);

export function familyModules(): GenFile[] {
  const themes = THEMES.map((name) => ({
    path: `src/generated/sdvtables/themes/${name}.ts`,
    text: `${HEADER}
import { STANDINGS } from "@sportsdataverse/examples/data";
import { defineTable } from "@sportsdataverse/sdvtables";
import { renderHTMLAsync } from "@sportsdataverse/sdvtables/html";
${CONTRACT}

export const meta = { title: ${q(`Theme: ${name}`)}, tags: ["theme", ${q(name)}] } satisfies ExampleMeta;

const spec = defineTable<(typeof STANDINGS)[number]>()
  .columns((c) => [
    c.logo("team", { league: "nfl" }),
    c.int("wins"),
    c.int("losses"),
    c.int("pf", { label: "PF" }),
    c.int("pa", { label: "PA" }),
    c.colorPills("net_epa", { label: "Net EPA/play", digits: 3, domain: [-0.2, 0.2] }),
  ])
  .theme(${q(name)}${THEME_OPTIONS[name] ?? ""})
  .title("AFC, 2024 regular season")
  .build();
export default await renderHTMLAsync(spec, STANDINGS);
`,
  }));
  const surfaces = Object.entries(SURFACE_LEAGUES).flatMap(([sport, leagues]) =>
    leagues.map((league) => ({
      path: `src/generated/sporty/surfaces/${sport}-${slug(league)}.ts`,
      text: `${HEADER}
import { surface } from "@sportsdataverse/sporty";
import { toSVG } from "@sportsdataverse/sporty/svg";
${CONTRACT}

export const meta = { title: ${q(`${sport}: ${league}`)}, tags: ["surface", ${q(sport)}, ${q(league)}] } satisfies ExampleMeta;

export default toSVG(surface(${q(sport)}, ${q(league)}), { width: 640 });
`,
    })),
  );
  return [...themes, ...surfaces];
}

/**
 * The registry (metadata for the gate and the pages) and the browser loaders: every example except `node` ones
 * (they import jsdom, fs, resvg) and `network` ones (the browser would download the real 18 MB manifest).
 */
export function registryModules(entries: readonly ExampleEntry[]): { registry: string; loaders: string } {
  const head = "// generated by examples/scripts/gen.ts - do not edit";
  const rows = entries.map(
    (e) =>
      `  { id: ${q(e.id)}, package: ${q(e.package)}, title: ${q(e.title)}, tags: ${q(e.tags)}, lang: ${q(e.lang)}, file: ${q(e.file)}, code: ${q(e.code)} },`,
  );
  const load = entries
    .filter((e) => !e.tags.includes("node") && !e.tags.includes("network"))
    .map((e) => `  ${q(e.id)}: () => import(${q(`./${e.file.slice(4).replace(/\.tsx?$/, ".js")}`)}),`);
  return {
    registry: `${head}\nimport type { ExampleEntry } from "./contract.js";\n\nexport const EXAMPLES: readonly ExampleEntry[] = [\n${rows.join("\n")}\n];\n`,
    loaders: `${head}\n/** Browser loaders: importing one runs that example. node and network examples are left out. */\nexport const LOADERS: Readonly<Record<string, () => Promise<{ default: unknown }>>> = {\n${load.join("\n")}\n};\n`,
  };
}
