import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { ExamplePackage, Prerendered } from "../src/contract.js";
import { overLimit, staticFile, svgDocument } from "./remark-live.js";

/** Section folder (second path segment of a gallery page) → sidebar label. Unknown sections use their folder name. */
const SECTIONS: Readonly<Record<string, string>> = {
  core: "Identity, colours, marks",
  plot: "Observable Plot",
  d3: "D3",
  react: "React",
  node: "Node and SSR",
  svg: "SVG renderer",
  surfaces: "Every surface",
  frames: "Frames, units, transforms",
  spec: "Table spec",
  themes: "Every theme",
  kinds: "Every cell kind",
  decorations: "Every decoration",
  html: "HTML renderer",
  api: "From the API docs",
};
const PACKAGES: Readonly<Record<ExamplePackage, string>> = {
  sdvplot: "@sportsdataverse/sdvplot",
  sporty: "@sportsdataverse/sporty",
  sdvtables: "@sportsdataverse/sdvtables",
};

/** Gallery page path of an example: its id, except docstring ids `api/<pkg>/<name>` live at `<pkg>/api/<name>`. */
export const pagePath = (e: Pick<Prerendered, "id" | "package">): string =>
  e.id.startsWith("api/") ? `${e.package}/api/${e.id.split("/").slice(2).join("/")}` : e.id;

export function readRows(outDir: string): Prerendered[] {
  const rows: Prerendered[] = [];
  const walk = (d: string): void => {
    for (const f of readdirSync(d, { withFileTypes: true })) {
      if (f.isDirectory()) walk(join(d, f.name));
      else if (f.name.endsWith(".json")) rows.push(JSON.parse(readFileSync(join(d, f.name), "utf8")));
    }
  };
  walk(outDir);
  return rows.sort((a, b) => (a.id < b.id ? -1 : 1));
}

const yaml = (s: string): string => JSON.stringify(s); // a JSON string is a valid YAML double-quoted scalar
const GENERATED = "{/* generated by examples/scripts/pages.ts - do not edit */}";

function write(file: string, text: string): void {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, text);
}

/** Write the gallery (an index per package, a page per example) and the static files for large outputs. */
export function writePages(outDir: string, docsDir: string): void {
  const rows = readRows(outDir);
  const gallery = join(docsDir, "docs/gallery");
  rmSync(gallery, { recursive: true, force: true });
  rmSync(join(docsDir, "static/examples"), { recursive: true, force: true });
  write(join(gallery, "_category_.json"), `${JSON.stringify({ label: "Gallery", position: 4 })}\n`);
  write(
    join(gallery, "index.mdx"),
    `---\ntitle: Gallery\nsidebar_position: 0\n---\n\n${GENERATED}\n\nEvery example on this site runs in CI before it is published. Pick a package:\n\n${(Object.keys(PACKAGES) as ExamplePackage[]).map((p) => `- [${PACKAGES[p]}](/gallery/${p}/) (${rows.filter((r) => r.package === p).length} examples)`).join("\n")}\n`,
  );
  for (const r of rows) {
    // The same file the gate writes (remark-live points <Live src> at it): an SVG served as a document needs xmlns.
    if (overLimit(r.markup)) {
      const file = staticFile(r);
      write(join(docsDir, "static", file), file.endsWith(".svg") ? svgDocument(r.markup) : r.markup);
    }
    const tags = r.tags.map((t) => `\`${t}\``).join(" · ");
    write(
      join(gallery, `${pagePath(r)}.mdx`),
      `---\ntitle: ${yaml(r.title)}\ndescription: ${yaml(`${PACKAGES[r.package]} example: ${r.title}`)}\n---\n\n${GENERATED}\n\n<Live id=${yaml(r.id)} />\n\n**Tags:** ${tags}. [All ${r.package} examples](/gallery/${r.package}/).\n`,
    );
  }
  for (const p of Object.keys(PACKAGES) as ExamplePackage[]) {
    const mine = rows.filter((r) => r.package === p);
    const order = (s: string): number => {
      const i = Object.keys(SECTIONS).indexOf(s);
      return i < 0 ? Number.MAX_SAFE_INTEGER : i;
    };
    const sections = [...new Set(mine.map((r) => pagePath(r).split("/")[1] ?? ""))].sort(
      (a, b) => order(a) - order(b),
    );
    const body = sections.map((s) => {
      const cards = mine
        .filter((r) => pagePath(r).split("/")[1] === s)
        .map((r) => `<Live id=${yaml(r.id)} thumb href=${yaml(`/gallery/${pagePath(r)}`)} />`);
      write(
        join(gallery, p, s, "_category_.json"),
        `${JSON.stringify({ label: SECTIONS[s] ?? s, collapsed: true })}\n`,
      );
      return `## ${SECTIONS[s] ?? s}\n\n<div className="sdv-gallery">\n${cards.join("\n")}\n</div>`;
    });
    write(
      join(gallery, p, "index.mdx"),
      `---\ntitle: ${yaml(`${PACKAGES[p]} gallery`)}\n---\n\n${GENERATED}\n\n${body.join("\n\n")}\n`,
    );
  }
}
